THREAD_JOIN_TIMEOUT = 2.0
DIRECTORIO_DATA = "data"
EXTENSION_DATA = ".dat"

# Superficies y agua por tipo
SUPERFICIE_PINO = 2.0
AGUA_INICIAL_PINO = 2
ALTURA_INICIAL_PINO = 1.0

SUPERFICIE_OLIVO = 3.0
AGUA_INICIAL_OLIVO = 5
ALTURA_INICIAL_OLIVO = 0.5

SUPERFICIE_LECHUGA = 0.10
AGUA_INICIAL_LECHUGA = 1

SUPERFICIE_ZANAHORIA = 0.15
AGUA_INICIAL_ZANAHORIA = 0

# Riego
CONSUMO_RIEGO_POR_LLAMADA = 10
TEMP_MIN_RIEGO = 8
TEMP_MAX_RIEGO = 15
HUMEDAD_MAX_RIEGO = 50
INTERVALO_CONTROL_RIEGO = 2.5
COOLDOWN_RIEGO = 3

# Sensores
INTERVALO_SENSOR_TEMPERATURA = 2.0
INTERVALO_SENSOR_HUMEDAD = 3.0
SENSOR_TEMP_MIN = -25
SENSOR_TEMP_MAX = 50
SENSOR_HUMEDAD_MIN = 0
SENSOR_HUMEDAD_MAX = 100

# Absorcion de agua (Strategy Pattern)
ABSORCION_SEASONAL_VERANO = 5
ABSORCION_SEASONAL_INVIERNO = 2
MES_INICIO_VERANO = 3  # Marzo (hemisferio sur)
MES_FIN_VERANO = 8  # Agosto

# Crecimiento arboles
CRECIMIENTO_PINO_POR_RIEGO = 0.10
CRECIMIENTO_OLIVO_POR_RIEGO = 0.01